# Generated by Django 5.0.6 on 2024-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclararPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=40)),
                ('Client', models.CharField(max_length=40)),
                ('Cadencia', models.CharField(max_length=40)),
                ('NumDoc', models.CharField(max_length=40)),
                ('Cantidad', models.CharField(max_length=40)),
                ('Horas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PiezaPrensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=40)),
                ('Client', models.CharField(max_length=40)),
                ('Cadencia', models.CharField(max_length=40)),
                ('NumDoc', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PiezaSoldadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=40)),
                ('Client', models.CharField(max_length=40)),
                ('Cadencia', models.CharField(max_length=40)),
                ('NumDoc', models.CharField(max_length=40)),
                ('Minuteria', models.CharField(max_length=40)),
            ],
        ),
    ]
